
package medicalrecord;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AWSMedicalRecord", targetNamespace = "http://medicalRecord/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AWSMedicalRecord {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<medicalrecord.PharmakoTreats>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnPharmakoTreats", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnPharmakoTreats")
    @ResponseWrapper(localName = "returnPharmakoTreatsResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnPharmakoTreatsResponse")
    public List<PharmakoTreats> returnPharmakoTreats(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<medicalrecord.PharmakoSideEffects>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnPharmakoSideEffects", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnPharmakoSideEffects")
    @ResponseWrapper(localName = "returnPharmakoSideEffectsResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnPharmakoSideEffectsResponse")
    public List<PharmakoSideEffects> returnPharmakoSideEffects(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<medicalrecord.Transaction>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnTransaction", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnTransaction")
    @ResponseWrapper(localName = "returnTransactionResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnTransactionResponse")
    public List<Transaction> returnTransaction();

    /**
     * 
     * @param arg0
     * @return
     *     returns medicalrecord.Patient
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnPatientById", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnPatientById")
    @ResponseWrapper(localName = "returnPatientByIdResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnPatientByIdResponse")
    public Patient returnPatientById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertTransaction", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertTransaction")
    @ResponseWrapper(localName = "insertTransactionResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertTransactionResponse")
    public boolean insertTransaction(
        @WebParam(name = "arg0", targetNamespace = "")
        Transaction arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertPharmakoSideEffect", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertPharmakoSideEffect")
    @ResponseWrapper(localName = "insertPharmakoSideEffectResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertPharmakoSideEffectResponse")
    public boolean insertPharmakoSideEffect(
        @WebParam(name = "arg0", targetNamespace = "")
        PharmakoSideEffects arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deletePharmakoTreat", targetNamespace = "http://medicalRecord/", className = "medicalrecord.DeletePharmakoTreat")
    @ResponseWrapper(localName = "deletePharmakoTreatResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.DeletePharmakoTreatResponse")
    public void deletePharmakoTreat(
        @WebParam(name = "arg0", targetNamespace = "")
        PharmakoTreats arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteTransaction", targetNamespace = "http://medicalRecord/", className = "medicalrecord.DeleteTransaction")
    @ResponseWrapper(localName = "deleteTransactionResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.DeleteTransactionResponse")
    public void deleteTransaction(
        @WebParam(name = "arg0", targetNamespace = "")
        Transaction arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deletePharmakoSideEffect", targetNamespace = "http://medicalRecord/", className = "medicalrecord.DeletePharmakoSideEffect")
    @ResponseWrapper(localName = "deletePharmakoSideEffectResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.DeletePharmakoSideEffectResponse")
    public void deletePharmakoSideEffect(
        @WebParam(name = "arg0", targetNamespace = "")
        PharmakoSideEffects arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertPharmakoTreat", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertPharmakoTreat")
    @ResponseWrapper(localName = "insertPharmakoTreatResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertPharmakoTreatResponse")
    public boolean insertPharmakoTreat(
        @WebParam(name = "arg0", targetNamespace = "")
        PharmakoTreats arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<medicalrecord.SideEffect>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnSideEffect", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnSideEffect")
    @ResponseWrapper(localName = "returnSideEffectResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnSideEffectResponse")
    public List<SideEffect> returnSideEffect();

    /**
     * 
     * @return
     *     returns java.util.List<medicalrecord.Patient>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnPatients", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnPatients")
    @ResponseWrapper(localName = "returnPatientsResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnPatientsResponse")
    public List<Patient> returnPatients();

    /**
     * 
     * @return
     *     returns java.util.List<medicalrecord.Clinic>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnClinics", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnClinics")
    @ResponseWrapper(localName = "returnClinicsResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnClinicsResponse")
    public List<Clinic> returnClinics();

    /**
     * 
     * @return
     *     returns java.util.List<medicalrecord.DoctorC>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnDoctors", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnDoctors")
    @ResponseWrapper(localName = "returnDoctorsResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnDoctorsResponse")
    public List<DoctorC> returnDoctors();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertDoctor", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertDoctor")
    @ResponseWrapper(localName = "insertDoctorResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertDoctorResponse")
    public boolean insertDoctor(
        @WebParam(name = "arg0", targetNamespace = "")
        DoctorC arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateRequest", targetNamespace = "http://medicalRecord/", className = "medicalrecord.UpdateRequest")
    @ResponseWrapper(localName = "updateRequestResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.UpdateRequestResponse")
    public boolean updateRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        Requests arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<medicalrecord.Disease>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnDisease", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnDisease")
    @ResponseWrapper(localName = "returnDiseaseResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnDiseaseResponse")
    public List<Disease> returnDisease();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDoctor", targetNamespace = "http://medicalRecord/", className = "medicalrecord.DeleteDoctor")
    @ResponseWrapper(localName = "deleteDoctorResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.DeleteDoctorResponse")
    public void deleteDoctor(
        @WebParam(name = "arg0", targetNamespace = "")
        DoctorC arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertClinic", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertClinic")
    @ResponseWrapper(localName = "insertClinicResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertClinicResponse")
    public boolean insertClinic(
        @WebParam(name = "arg0", targetNamespace = "")
        Clinic arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertPatient", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertPatient")
    @ResponseWrapper(localName = "insertPatientResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertPatientResponse")
    public boolean insertPatient(
        @WebParam(name = "arg0", targetNamespace = "")
        Patient arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertDisease", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertDisease")
    @ResponseWrapper(localName = "insertDiseaseResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertDiseaseResponse")
    public boolean insertDisease(
        @WebParam(name = "arg0", targetNamespace = "")
        Disease arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertUser", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertUser")
    @ResponseWrapper(localName = "insertUserResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertUserResponse")
    public boolean insertUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<medicalrecord.Requests>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnRequests", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnRequests")
    @ResponseWrapper(localName = "returnRequestsResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.ReturnRequestsResponse")
    public List<Requests> returnRequests();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertPharmako", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertPharmako")
    @ResponseWrapper(localName = "insertPharmakoResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertPharmakoResponse")
    public boolean insertPharmako(
        @WebParam(name = "arg0", targetNamespace = "")
        Pharmako arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertSideEffect", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertSideEffect")
    @ResponseWrapper(localName = "insertSideEffectResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.InsertSideEffectResponse")
    public boolean insertSideEffect(
        @WebParam(name = "arg0", targetNamespace = "")
        SideEffect arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePatient", targetNamespace = "http://medicalRecord/", className = "medicalrecord.UpdatePatient")
    @ResponseWrapper(localName = "updatePatientResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.UpdatePatientResponse")
    public boolean updatePatient(
        @WebParam(name = "arg0", targetNamespace = "")
        Patient arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteToUse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.DeleteToUse")
    @ResponseWrapper(localName = "deleteToUseResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.DeleteToUseResponse")
    public void deleteToUse(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteClinic", targetNamespace = "http://medicalRecord/", className = "medicalrecord.DeleteClinic")
    @ResponseWrapper(localName = "deleteClinicResponse", targetNamespace = "http://medicalRecord/", className = "medicalrecord.DeleteClinicResponse")
    public void deleteClinic(
        @WebParam(name = "arg0", targetNamespace = "")
        Clinic arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
