
package healthservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AWSHealthService", targetNamespace = "http://healthService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AWSHealthService {


    /**
     * 
     * @return
     *     returns java.util.List<healthservice.Perscription>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnPrescritpions", targetNamespace = "http://healthService/", className = "healthservice.ReturnPrescritpions")
    @ResponseWrapper(localName = "returnPrescritpionsResponse", targetNamespace = "http://healthService/", className = "healthservice.ReturnPrescritpionsResponse")
    public List<Perscription> returnPrescritpions();

    /**
     * 
     * @return
     *     returns java.util.List<healthservice.Disease>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnDiseases", targetNamespace = "http://healthService/", className = "healthservice.ReturnDiseases")
    @ResponseWrapper(localName = "returnDiseasesResponse", targetNamespace = "http://healthService/", className = "healthservice.ReturnDiseasesResponse")
    public List<Disease> returnDiseases();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnReport", targetNamespace = "http://healthService/", className = "healthservice.ReturnReport")
    @ResponseWrapper(localName = "returnReportResponse", targetNamespace = "http://healthService/", className = "healthservice.ReturnReportResponse")
    public String returnReport();

    /**
     * 
     * @return
     *     returns java.util.List<healthservice.Pharmako>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnPharmaka", targetNamespace = "http://healthService/", className = "healthservice.ReturnPharmaka")
    @ResponseWrapper(localName = "returnPharmakaResponse", targetNamespace = "http://healthService/", className = "healthservice.ReturnPharmakaResponse")
    public List<Pharmako> returnPharmaka();

}
