
package healthservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AWSHealthServiceImplService", targetNamespace = "http://healthService/", wsdlLocation = "http://25.48.208.207:8080/epl362/HealthManageWS?wsdl")
public class AWSHealthServiceImplService
    extends Service
{

    private final static URL AWSHEALTHSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AWSHEALTHSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName AWSHEALTHSERVICEIMPLSERVICE_QNAME = new QName("http://healthService/", "AWSHealthServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://25.48.208.207:8080/epl362/HealthManageWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AWSHEALTHSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        AWSHEALTHSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AWSHealthServiceImplService() {
        super(__getWsdlLocation(), AWSHEALTHSERVICEIMPLSERVICE_QNAME);
    }

    public AWSHealthServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AWSHEALTHSERVICEIMPLSERVICE_QNAME, features);
    }

    public AWSHealthServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, AWSHEALTHSERVICEIMPLSERVICE_QNAME);
    }

    public AWSHealthServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AWSHEALTHSERVICEIMPLSERVICE_QNAME, features);
    }

    public AWSHealthServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AWSHealthServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AWSHealthService
     */
    @WebEndpoint(name = "AWSHealthServiceImplPort")
    public AWSHealthService getAWSHealthServiceImplPort() {
        return super.getPort(new QName("http://healthService/", "AWSHealthServiceImplPort"), AWSHealthService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AWSHealthService
     */
    @WebEndpoint(name = "AWSHealthServiceImplPort")
    public AWSHealthService getAWSHealthServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://healthService/", "AWSHealthServiceImplPort"), AWSHealthService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AWSHEALTHSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw AWSHEALTHSERVICEIMPLSERVICE_EXCEPTION;
        }
        return AWSHEALTHSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
