
package clinical;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AWSClinicalStaffImplService", targetNamespace = "http://clinical/", wsdlLocation = "http://25.48.208.207:8080/epl362/ClinicalWS?wsdl")
public class AWSClinicalStaffImplService
    extends Service
{

    private final static URL AWSCLINICALSTAFFIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AWSCLINICALSTAFFIMPLSERVICE_EXCEPTION;
    private final static QName AWSCLINICALSTAFFIMPLSERVICE_QNAME = new QName("http://clinical/", "AWSClinicalStaffImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://25.48.208.207:8080/epl362/ClinicalWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AWSCLINICALSTAFFIMPLSERVICE_WSDL_LOCATION = url;
        AWSCLINICALSTAFFIMPLSERVICE_EXCEPTION = e;
    }

    public AWSClinicalStaffImplService() {
        super(__getWsdlLocation(), AWSCLINICALSTAFFIMPLSERVICE_QNAME);
    }

    public AWSClinicalStaffImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AWSCLINICALSTAFFIMPLSERVICE_QNAME, features);
    }

    public AWSClinicalStaffImplService(URL wsdlLocation) {
        super(wsdlLocation, AWSCLINICALSTAFFIMPLSERVICE_QNAME);
    }

    public AWSClinicalStaffImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AWSCLINICALSTAFFIMPLSERVICE_QNAME, features);
    }

    public AWSClinicalStaffImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AWSClinicalStaffImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AWSClinicalStaff
     */
    @WebEndpoint(name = "AWSClinicalStaffImplPort")
    public AWSClinicalStaff getAWSClinicalStaffImplPort() {
        return super.getPort(new QName("http://clinical/", "AWSClinicalStaffImplPort"), AWSClinicalStaff.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AWSClinicalStaff
     */
    @WebEndpoint(name = "AWSClinicalStaffImplPort")
    public AWSClinicalStaff getAWSClinicalStaffImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://clinical/", "AWSClinicalStaffImplPort"), AWSClinicalStaff.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AWSCLINICALSTAFFIMPLSERVICE_EXCEPTION!= null) {
            throw AWSCLINICALSTAFFIMPLSERVICE_EXCEPTION;
        }
        return AWSCLINICALSTAFFIMPLSERVICE_WSDL_LOCATION;
    }

}
